name: Create Tag

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ayumu838/action-get-next-tag@2.0
        id: get-next-tag

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: '${{ steps.get-next-tag.outputs.tag }}'
          message: 'PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
